apiVersion: v1
kind: Service
metadata:
  name: pg-citus-dataset-worker
  labels:
    app: citus-dataset-worker
spec:
  ports:
  - port: 5432
    name: psql
  clusterIP: None
  selector:
    app: citus-dataset-worker
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: citus-dataset-worker
  name: pg-citus-dataset-worker
spec:
  replicas: 5
  selector:
    matchLabels:
      app: citus-dataset-worker
  serviceName: "pg-citus-dataset-worker"
  template:
    metadata:
      labels:
        app: citus-dataset-worker
        citusType: "citus-dataset-worker"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: db
                operator: In
                values:
                - "true"      
      containers:
        - env:
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          - name: POSTGRES_DB
            value: datasets
          - name: POSTGRES_HOST_AUTH_METHOD
            value: scram-sha-256
          - name: POSTGRES_INITDB_ARGS
            value: --auth-host=scram-sha-256
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: citus-secrets
                key: password
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: citus-secrets
                key: password
          image: eeacms/citus-postgis:1.0
          imagePullPolicy: Always
          name: citus-worker
          volumeMounts:
          - name: storage
            mountPath: /var/lib/postgresql/data
          ports:
            - containerPort: 5432
              name: psql
          readinessProbe:
            exec:
              command:
              - echo
              - "test"
            initialDelaySeconds: 60
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        storageClassName: reportnet
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi